name: seller_side_uo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.29.0
  firebase_database: ^10.5.1
  flutter:
    sdk: flutter
  google_fonts: 6.2.0
  google_maps_flutter: ^2.6.0
  image_picker: ^1.0.7
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf # Specify the path to your dummy font file
